models:
  "deepseek-r1:1.5b":
    vocab_type: "bpe"
    description: "DeepSeek R1 1.5B Qwen model"
    recommended_quantization: "q4_k_m"
    tags: 
      - medical
      - reasoning
      - distilled
    template: |
      {{- if .System }}{{ .System }}{{ end }}
      User: {prompt}
      Assistant:
    
  "deepseek-r1:7b":
    vocab_type: "bpe"
    description: "DeepSeek R1 7B Qwen model"
    recommended_quantization: "q4_k_m"
    tags:
      - medical
      - reasoning
    template: |
      {{- if .System }}{{ .System }}{{ end }}
      User: {prompt}
      Assistant:
    
  "deepseek-r1:14b":
    vocab_type: "bpe"
    description: "DeepSeek R1 14B Qwen model"
    recommended_quantization: "q4_k_m"
    tags:
      - medical
      - reasoning
    template: |
      {{- if .System }}{{ .System }}{{ end }}
      User: {prompt}
      Assistant:

  "deepseek-ai/deepseek-coder-6.7b-instruct":
    vocab_type: "bpe"
    description: "DeepSeek Coder 6.7B Instruct model"
    recommended_quantization: "q4_k_m"
    tags:
      - code
      - instruct 